name = "edgetunnel3c" # 项目名称
type = "javascript"   # 使用的 Worker 类型，确保与代码匹配

[build]
upload = { format = "service-worker" }

# 指定入口文件，_worker.js 是你的主入口文件
main = "_worker.js"

[vars]
# 如果你有环境变量，可以在这里定义
SENSITIVE_URL = "https://example.com"
