name = "edgetunnel3c"
type = "javascript"

# Set the directory for Pages
pages_build_output_dir = "./"

# Compatibility date
compatibility_date = "2024-12-08"

[build]
upload_format = "service-worker"
