name = "ipbc"  # 手动修改同cloudflare中部署的项目名
type = "javascript"  # 使用标准 JavaScript 模式

[build]
upload = { format = "service-worker" }  # 定义部署模式为 Service Worker

main = "_worker.js"  # 指定入口文件

[vars]
SENSITIVE_URL = "https://example.com"  # 示例环境变量，实际替换为你需要的
